import { images } from ".";

export const Items = [
    {
        id: 1,
        kategori: 'crewneck',
        namaProduk: 'Crewneck Bulls CN-BL',
        harga: 330000,
        size: '90',
        panjang: '67',
        lebar: '53',
        deskripsi: 'Detail produk minus crack halus kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.cnBL1,
        listGambar: [
            images.cnBL1,
            images.cnBL2,
            images.cnBL3,
        ],
    },
    {
        id: 2,
        kategori: 'crewneck',
        namaProduk: 'Crewneck Champion CN-CH',
        harga: 140000,
        size: 'L',
        panjang: '65',
        lebar: '53',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.cnCH1,
        listGambar: [
            images.cnCH1,
            images.cnCH2,
            images.cnCH3,
        ],
    },
    {
        id: 3,
        kategori: 'crewneck',
        namaProduk: 'Crewneck Dickies CN-DK',
        harga: 150000,
        size: 'M',
        panjang: '66',
        lebar: '58',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman minus noda',
        gambarProduk: images.cnDK1,
        listGambar: [
            images.cnDK1,
            images.cnDK2,
            images.cnDK3,
        ],
    },
    {
        id: 4,
        kategori: 'crewneck',
        namaProduk: 'Crewneck New Balance CN-NB',
        harga: 200000,
        size: 'L',
        panjang: '70',
        lebar: '60',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.cnNB1,
        listGambar: [
            images.cnNB1,
            images.cnNB2,
            images.cnNB3,
        ],
    },
    {
        id: 5,
        kategori: 'flanel',
        namaProduk: 'Flanel Flannel Original FN-FNL',
        harga: 90000,
        size: 'XL',
        panjang: '75',
        lebar: '55',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat',
        gambarProduk: images.fnFNL1,
        listGambar: [
            images.fnFNL1,
            images.fnFNL2,
            images.fnFNL3,
        ],
    },
    {
        id: 6,
        kategori: 'flanel',
        namaProduk: 'Flanel Neyries FN-NYR',
        harga: 80000,
        size: 'L',
        panjang: '70',
        lebar: '60',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat',
        gambarProduk: images.fnNYR1,
        listGambar: [
            images.fnNYR1,
            images.fnNYR2,
            images.fnNYR3,
        ],
    },
    {
        id: 7,
        kategori: 'flanel',
        namaProduk: 'Flanel Qualitu Garment FN-QL',
        harga: 75000,
        size: 'XL',
        panjang: '78',
        lebar: '62',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat',
        gambarProduk: images.fnQL1,
        listGambar: [
            images.fnQL1,
            images.fnQL2,
            images.fnQL3,
        ],
    },
    {
        id: 8,
        kategori: 'flanel',
        namaProduk: 'Flanel Robinson FN-RB',
        harga: 85000,
        size: 'XL',
        panjang: '73',
        lebar: '58',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat',
        gambarProduk: images.fnRB1,
        listGambar: [
            images.fnRB1,
            images.fnRB2,
            images.fnRB3,
        ],
    },
    {
        id: 9,
        kategori: 'hoodie',
        namaProduk: 'Hoodie Dickies HD-DK',
        harga: 200000,
        size: 'XL',
        panjang: '77',
        lebar: '63',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.hdDK1,
        listGambar: [
            images.hdDK1,
            images.hdDK2,
            images.hdDK3,
        ],
    },
    {
        id: 10,
        kategori: 'hoodie',
        namaProduk: 'Hoodie G.A.P. HD-GAP',
        harga: 220000,
        size: 'XL',
        panjang: '73',
        lebar: '66',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.hdGAP1,
        listGambar: [
            images.hdGAP1,
            images.hdGAP2,
            images.hdGAP3,
        ],
    },
    {
        id: 11,
        kategori: 'hoodie',
        namaProduk: 'Hoodie N.B.A. HD-NBA',
        harga: 300000,
        size: 'XXL',
        panjang: '78',
        lebar: '66',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.hdNBA1,
        listGambar: [
            images.hdNBA1,
            images.hdNBA2,
            images.hdNBA3,
        ],
    },
    {
        id: 12,
        kategori: 'hoodie',
        namaProduk: 'Hoodie Off White HD-OW',
        harga: 250000,
        size: 'XL',
        panjang: '75',
        lebar: '62',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.hdOW1,
        listGambar: [
            images.hdOW1,
            images.hdOW2,
            images.hdOW3,
        ],
    },
    {
        id: 13,
        kategori: 'jacket',
        namaProduk: 'Jacket Outdoor BlackYak JK-BL',
        harga: 210000,
        size: 'XL',
        panjang: '73',
        lebar: '62',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.jkBL1,
        listGambar: [
            images.jkBL1,
            images.jkBL2,
            images.jkBL3,
        ],
    },
    {
        id: 14,
        kategori: 'jacket',
        namaProduk: 'Jacket Outdoor K2 JK-K2',
        harga: 150000,
        size: 'M',
        panjang: '63',
        lebar: '50',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.jkKK1,
        listGambar: [
            images.jkKK1,
            images.jkKK2,
            images.jkKK3,
        ],
    },
    {
        id: 15,
        kategori: 'jacket',
        namaProduk: 'Jacket Outdoor TNF Black JK-TNB',
        harga: 250000,
        size: 'XL',
        panjang: '75',
        lebar: '62',
        deskripsi: 'Saku Samping | Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.jkTNB1,
        listGambar: [
            images.jkTNB1,
            images.jkTNB2,
            images.jkTNB3,
        ],
    },
    {
        id: 16,
        kategori: 'jacket',
        namaProduk: 'Jacket Outdoor TNF Red JK-TNF',
        harga: 350000,
        size: 'XL',
        panjang: '74',
        lebar: '67',
        deskripsi: 'Detail produk kondisi over all good condition warna pekat karet aman',
        gambarProduk: images.jkTNF1,
        listGambar: [
            images.jkTNF1,
            images.jkTNF2,
            images.jkTNF3,
        ],
    },
]